# Exported from Render on 2025-06-28T14:28:12Z
services:
- type: web
  name: inventario_api
  runtime: node
  repo: https://github.com/cristiangil28/inventario_api
  plan: free
  envVars:
  - key: DB_PASSWORD
    sync: false
  - key: DB_USERNAME
    sync: false
  - key: DB_DATABASE
    sync: false
  - key: DB_PORT
    sync: false
  - key: DB_HOST
    sync: false
  - key: DB_CONNECTION
    sync: false
  - key: APP_KEY
    sync: false
  - key: APP_ENV
    sync: false
  region: oregon
  buildCommand: composer install --no-dev
  startCommand: php artisan serve --host=0.0.0.0 --port=10000
  autoDeployTrigger: commit
version: "1"
